name: Run Python Tests
on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python src/test_runner.py
      - name: Create PR if Tests pass
        if: success() || failure()
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
